version: "3.7"
services:
  db:
    image: "postgres:14"
    container_name: "ddd_nest_db"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: password
    volumes:
      - "./dev/db/initdb/:/docker-entrypoint-initdb.d/"
      - "postgresqlvolume:/var/lib/postgresql/data"
volumes:
  postgresqlvolume:
